<?php

/**
 * @file
 * Implements handlers for an input filter that returns the number of available machines in Middlebury labs
 */

/**
 * Implements hook_filter_info().
 */
function middlebury_labserver_filter_info() {
  $filters['middlebury_labserver_filter'] = array(
    'title' => t('Middlebury Lab Server Filter'),
    'description' => t('Returns the number of available machines in Middlebury labs.'),
    'process callback' => '_middlebury_labserver_process',
  );
  return $filters;
}

/**
 * Implements hook_filter_FILTER_process().
 */
function _middlebury_labserver_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  return preg_replace_callback('/\[labserver\s?([^\]]*)\]/', "middlebury_labserver_replace", $text);
}

/**
 * Answer the number of available machines in Middlebury labs.
 *
 * @param $matches
 *   The matches array provided by preg_replace_callback().
 *
 * @return The number of available machines in Middlebury labs.
 */
function middlebury_labserver_replace($matches) {
  if (!empty($matches[1]))
    $labs = preg_split('/,/', $matches[1]);

  $file = file_get_contents('http://labserver.middlebury.edu:8080/public/xml-client.jsp');
  $file = str_replace('& ', '&amp; ', $file);
  $xml = simplexml_load_string($file);

  $available = 0;
  if ($xml !== FALSE) {
    foreach ($xml->lab as $lab) {
      if (!empty($labs) && !in_array((int)$lab->attributes()->id, $labs))
        continue;

      foreach ($lab->client as $client) {
        if ((string)$client->attributes()->status == 'available') {
          $available++;
        }
      }
    }
  }

  return $available;
}