<?php

function middlebury_tinymce_wysiwyg_editor_settings_alter(&$settings, &$context) {
  /*
  // Disable TinyMCE for admins editing Full HTML nodes.
  if (user_access('administer nodes') && is_numeric(arg(3)) && arg(4) == 'edit') {
    $node = node_load(arg(3));
    if ($node->format == 2) {
      unset($init);
    }
  }

  // Disable TinyMCE for Bibliography Module content type and Planning Goal Summary form.
  if (arg(1) == '477865' || in_array($textarea_name, $disabled_fields)) {
    unset($init);
  }
  */
  $settings['width'] = '450px';
  $settings['content_css'] .= ',' . drupal_get_path('module', 'middlebury_tinymce') . '/middlebury_tinymce.css';
  $settings['theme_advanced_resize_horizontal'] = TRUE;
  $settings['theme_advanced_buttons1'] = 'bold,italic,underline,strikethrough,sub,sup,separator,bullist,numlist,outdent,indent,separator,justifyleft,justifycenter,justifyright,justifyfull,ltr,rtl,separator,preview,help';
  $settings['theme_advanced_buttons2'] = 'formatselect,styleselect,separator,cut,copy,paste,pastetext,pasteword,separator,removeformat,cleanup,code,separator,undo,redo';
  $settings['theme_advanced_buttons3'] = 'mm_media,image,separator,link,unlink,anchor,separator,hr,nonbreaking,charmap,blockquote,insertdate,inserttime,separator,search,replace,spellchecker,print';
  $settings['theme_advanced_buttons4'] = 'tablecontrols,separator';
}