<footer id="midd_footer" class="footer">
  <nav class="container">
    <ul> 
      <li class="schoolsabroad_contact"><a href="<?php print $base_path; ?>sa/contact">Contact Us<span></span></a></li> 
      <li class="schoolsabroad_directory"><a href="http://go.middlebury.edu/directory">Directory<span></span></a></li> 
      <li class="schoolsabroad_giving"><a href="<?php print $base_path; ?>giving/priorities/schools_abroad">Giving to Schools Abroad<span></span></a></li>
      <li class="quick_footer quick_go"><a href="http://go.middlebury.edu">Quick Links<span></span></a>
        <div class="contents">
          <ul class="quick_footer">
            <li><a href="http://go.middlebury.edu/bannerweb">BannerWeb</a></li>
            <li><a href="http://go.middlebury.edu/webmail">Webmail</a></li>
            <li><a href="http://go.middlebury.edu/directory">Directory</a></li>
            <li><a href="http://go.middlebury.edu/library">Library</a></li>
            <li><a href="http://go.middlebury.edu/helpdesk">Technology Help</a></li>
            <li><a href="http://go.middlebury.edu/calendar?academic">Academic Calendar</a></li>
            <li><a href="http://go.middlebury.edu/web/about">About this Site</a></li>
            <li><a href="http://go.middlebury.edu/er">Emergency</a></li>
          </ul>
          <ul class="quick_footer">
            <li><a href="http://go.middlebury.edu/jobseekers">Job Seekers</a></li>
            <li><a href="http://go.middlebury.edu/bookstore">Bookstore</a></li>
            <li><a href="http://boxoffice.middlebury.edu">Box Office</a></li>
            <li><a href="http://museum.middlebury.edu">Museum of Art</a></li>
            <li><a href="http://go.middlebury.edu/campusmap">Campus Maps</a></li>
            <li><a href="http://go.middlebury.edu/privacy">Privacy</a></li>
            <li><a href="http://go.middlebury.edu/copyright">Copyright</a></li>
          </ul>
        </div>
      </li>
    </ul>
    <a href="<?php print $base_path; ?>" class="footer_wordmark"><img src="//cdn.middlebury.edu/middlebury.edu/2010/images/footer_wordmark.gif" width="94" height="30" alt="&laquo; Return to Middlebury.edu"></a>
    <div class="clear"></div>
  </nav>
</footer>
<div id="midd_footer_panel" class="footer_panel"></div>