<footer id="midd_footer" class="footer">
  <nav class="container">
    <ul>
      <li class="languageschools_students"><a href="<?php print $base_path; ?>ls/students">Current Students<span></span></a></li>
      <li class="languageschools_families"><a href="<?php print $base_path; ?>ls/parents">Families<span></span></a></li>
      <li class="languageschools_alumni"><a href="<?php print $base_path; ?>ls/alumni">Current Students<span></span></a></li>
      <li class="languageschools_contact"><a href="<?php print $base_path; ?>ls/contact">Contact Us<span></span></a></li>
    </ul>
    <a href="<?php print $base_path; ?>" class="footer_wordmark"><img src="//cdn.middlebury.edu/middlebury.edu/2010/images/footer_wordmark.gif" width="94" height="30" alt="&laquo; Return to Middlebury.edu"></a>
    <div class="clear"></div>
  </nav>
</footer>
<div id="midd_footer_panel" class="footer_panel"></div>