<?php

/**
 * @file
 * Implements handlers for alerting Middlebury about emergencies.
 */

/**
 * Implements hook_menu().
 */
function middlebury_alert_menu() {
  $items['admin/settings/middlebury_alert'] = array(
    'title' => 'Middlebury Alert Settings',
    'description' => 'Configure settings for the Middlebury Alert system.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('middlebury_alert_admin_settings'),
    'access arguments' => array('administer middlebury_alert'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Provide settings page.
 *
 * @return array
 */
function middlebury_alert_admin_settings() {
  $form['middlebury_alert_power'] = array(
    '#type' => 'checkbox',
    '#title' => t('Turn Middlebury Alert On'),
    '#default_value' => variable_get('middlebury_alert_power', 0),
  );
  $form['middlebury_alert_level'] = array(
    '#type' => 'radios',
    '#title' => t('Alert Level'),
    '#default_value' => variable_get('middlebury_alert_level', 'Notice'),
    '#options' => array(
      'Notice' => t('Notice'),
      'Warning' => t('Warning'),
      'Emergency' => t('Emergency')
    ),
  );
  $form['middlebury_alert_feed'] = array(
    '#type' => 'textfield',
    '#title' => t('Alerts RSS Feed'),
    '#default_value' => variable_get('middlebury_alert_feed', 'https://sites.google.com/site/middalert/alerts/posts.xml'),
    '#size' => 100,
    '#required' => TRUE,
  );
  $form['middlebury_alert_override'] = array(
    '#type' => 'textfield',
    '#title' => t('Override Alert Message'),
    '#default_value' => variable_get('middlebury_alert_override', ''),
    '#maxlength' => 1000,
    '#size' => 100,
  );
  $form['colors'] = array(
    '#type' => 'fieldset',
    '#title' => t('Alert Colors'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['colors']['middlebury_alert_notice_bg'] = array(
    '#type' => 'textfield',
    '#title' => t('Notice Background'),
    '#default_value' => variable_get('middlebury_alert_notice_bg', '#BEDA90'),
    '#size' => 10,
    '#required' => TRUE,
  );
  $form['colors']['middlebury_alert_notice_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Notice Text'),
    '#default_value' => variable_get('middlebury_alert_notice_text', '#003468'),
    '#size' => 10,
    '#required' => TRUE,
  );
  $form['colors']['middlebury_alert_warning_bg'] = array(
    '#type' => 'textfield',
    '#title' => t('Warning Background'),
    '#default_value' => variable_get('middlebury_alert_warning_bg', '#FDDB40'),
    '#size' => 10,
    '#required' => TRUE,
  );
  $form['colors']['middlebury_alert_warning_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Warning Text'),
    '#default_value' => variable_get('middlebury_alert_warning_text', '#003468'),
    '#size' => 10,
    '#required' => TRUE,
  );
  $form['colors']['middlebury_alert_emergency_bg'] = array(
    '#type' => 'textfield',
    '#title' => t('Emergency Background'),
    '#default_value' => variable_get('middlebury_alert_emergency_bg', '#AA1E35'),
    '#size' => 10,
    '#required' => TRUE,
  );
  $form['colors']['middlebury_alert_emergency_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Emergency Text'),
    '#default_value' => variable_get('middlebury_alert_emergency_text', '#fff'),
    '#size' => 10,
    '#required' => TRUE,
  );
  $form['#submit'][] = 'middlebury_alert_admin_settings_submit';
  return system_settings_form($form);
}

/**
 * Implements hook_form_submit().
 */
function middlebury_alert_admin_settings_submit(&$form_id, &$form_values) {
  $fields = array(
    'ACCESS_KEY' => urlencode('PleaseLetMePurgeURLs.PrettyPlease!'),
    'PATH_REGEX' => urlencode('.*'),
  );
  $fields_string = '';
  foreach ($fields as $k => $v) $fields_string .= $k . '=' . $v . '&';
  rtrim($fields_string, '&');

  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, 'http://supersoaker.middlebury.edu/admin_api/purge_varnish_url_from_all.php');
  curl_setopt($ch, CURLOPT_POST, count($fields));
  curl_setopt($ch, CURLOPT_POSTFIELDS, $fields_string);
  $body = curl_exec($ch);
  curl_close($ch);

  global $user;
  $variables = array(
    '%user' => $user->name,
    '%power' => $form_values['values']['middlebury_alert_power'] ? 'On' : 'Off',
    '%level' => $form_values['values']['middlebury_alert_level'],
    '%feed' => $form_values['values']['middlebury_alert_feed'],
    '%override' => $form_values['values']['middlebury_alert_override'],
  );
  $message = '%user turned the alert %power with alert level %level reading from %feed and override message "%override".';
  watchdog('middlebury_alert', $message, $variables, WATCHDOG_ALERT, NULL);
}

/**
 * Implements hook_permission().
 */
function middlebury_alert_permission() {
  return array('administer middlebury_alert');
}

/**
 * Answer the current alert message.
 *
 * @return string
 */
function middlebury_alert_message() {
  $message = variable_get('middlebury_alert_override', '');
  $feed_url = variable_get('middlebury_alert_feed', '');

  if ($message == '' && $feed_url != '') {
    module_load_include('inc', 'rss_page', 'simplepie');
    $feed = new SimplePie();
    $feed->set_feed_url($feed_url);
    $feed->enable_cache(false);
    $feed->init();
    $feed->handle_content_type();
    if (!$feed->error()) {
      $alert = $feed->get_item();

      $title = $alert->get_title();
      $link = $alert->get_permalink();

      $title = $title;

      $matches = array();
      if (preg_match('/\[(NOTICE|WARNING|EMERGENCY)\]\s?/i', $title, $matches)) {
        variable_set('middlebury_alert_level', drupal_ucfirst($matches[1]));

        $title = str_replace($matches[0], '', $title);
      }

      $message = '<a href="' . $link . '">' . $title . '</a>';
    }
  }

  return $message;
}

/**
 * Answer the current alert level background color.
 *
 * @return string
 */
function middlebury_alert_background() {
  $level = strtolower(variable_get('middlebury_alert_level', 'Notice'));
  return variable_get('middlebury_alert_'. $level .'_bg', '#BEDA90');
}

/**
 * Answer the current alert level text color.
 * 
 * @return string
 */
function middlebury_alert_text() {
  $level = strtolower(variable_get('middlebury_alert_level', 'Notice'));
  return variable_get('middlebury_alert_'. $level .'_text', '#003468');
}