<?php

function middlebury_external_links_filter($op, $delta = 0, $format = -1, $text = '') {
  switch($op) {
    case 'list':
      return array(0 => t('Middlebury External Links Filter'));

    case 'description':
      return t('Forces external links in submitted content to open in a new window.');

    case 'process':
      return preg_replace_callback('/<a (?:href=["\']?http:\/\/([^"\']+)[^>]+)/i', "middlebury_external_links_replace", $text);

    default:
      return $text;
  }
}

function middlebury_external_links_replace($matches) {
  if (strpos($matches[0], 'target="') !== FALSE ||
      strpos($matches[1], $_SERVER['HTTP_HOST']) !== FALSE) {
    return $matches[0];
  }

  return $matches[0] .' target="_blank"';
}